deep_learning = [
    "('deep', 'learn')",
    "kera",
    "('neural', 'network')",
    "tensorflow",
]

machine_learning = [
    "classif",
    "cluster",
    "ensembl",
    "('gradient', 'boost')",
    "graph",
    "knn",
    "machin",
    "model",
    "('mont', 'carlo')",
    "('natur', 'languag')",
    "('parallel', 'process')",
    "('random', 'forest')",
    "sentiment",
    "spark",
    "supervis",
    "('text', 'mine')",
    "tree",
    "unsupervis",
]

analytics = [
    "analysi",
    "anova",
    "arima",
    "('analyz', 'data')",
    "covari",
    "bayesian",
    "dataanalyt",
    "('databas', 'manag')",
    "eigenvalu",
    "eigenvector" "heteroscedast",
    "('linear', 'regress')",
    "logist",
    "multicollinear",
    "multivari",
    "mysql",
    "nosql",
    "('odd', 'ratio')",
    "outlier",
    "precis",
    "('princip', 'compon')",
    "python",
    "r",
    "recal",
    "regress",
    "sensit",
    "specif",
    "('stochast', 'model')",
    "tableau",
    "('time', 'seri')",
]

management = ["busi", "('busi', 'analyt')", "leadership", "manag", "strateg"]
