programs = {
    "American University: MSBA": "Business School",
    "Columbia University: MSDS": "Technical School",
    "Cornell University: MPS": "Technical School",
    "Drexel University: MSDS": "Technical School",
    "Duke University: MQM": "Business School",
    "Harvard University: MSDS": "Technical School",
    "Indiana University: MSDS (all-tracks)": "Technical School",
    "Illinois Institute of Technology: MSDS": "Technical School",
    "Johns Hopkins: MSDS": "Technical School",
    "NC State University: Institute for Advanced Analytics": "Technical School",
    "Northeastern University: MSDS": "Technical School",
    "SMU: MSDS": "Technical School",
    "Syracuse University: MSDS": "Technical School",
    "University of California Berkeley: MSDS": "Technical School",
    "University of Dayton: MSBN": "Business School",
    "University of Denver: MSDS": "Technical School",
    "University of Michigan: MSDS": "Technical School",
    "University of Missouri: MSDS": "Technical School",
    "University of Notre Dame: MSBA": "Business School",
    "University of San Diego: Master of Advanced Study in Data Science": "Technical School",
    "University of Virginia:  MSDS (non-dual)": "Technical School",
    "University of Wisconsin: MSDS (Online)": "Technical School",
    "Wake Forest University: MSBA": "Business School",
    "William and Mary: MSBA": "Business School",
}
