programs = {
    "American University: MSBA": "https://onlinebusiness.american.edu/programs/analytics/curriculum/",
    "Columbia University: MSDS": "https://datascience.columbia.edu/education/programs/m-s-in-data-science/",
    "Cornell University: MPS": "https://stat.cornell.edu/academics/mps/mps-degree-requirements-and-regulations",
    "Drexel University: MSDS": "http://catalog.drexel.edu/graduate/collegeofcomputingandinformatics/datascience/#degreerequirementstext",
    "Duke University: MQM": "https://www.fuqua.duke.edu/programs/mqm-business-analytics/curriculum",
    "Harvard University: MSDS": "https://www.seas.harvard.edu/applied-computation/courses",
    "Indiana University: MSDS (all-tracks)": "https://bulletins.iu.edu/iub/sice/2020-2021/graduate/degree-programs/master-of-data-science/index.shtml",
    "Illinois Institute of Technology: MSDS": "http://bulletin.iit.edu/graduate/colleges/computing/applied-mathematics/master-data-science/#programrequirementstext",
    "Johns Hopkins: MSDS": "https://ep.jhu.edu/programs/data-science/courses/",
    "NC State University: Institute for Advanced Analytics": "https://analytics.ncsu.edu/?page_id=123",
    "Northeastern University: MSDS": "https://www.northeastern.edu/graduate/program/master-of-science-in-data-science-5256/",
    "SMU: MSDS": "https://datascience.smu.edu/academics/courses/",
    "Syracuse University: MSDS": "https://onlinegrad.syracuse.edu/information-science/academics/#applied-data-science",
    "University of California Berkeley: MSDS": "https://ischoolonline.berkeley.edu/data-science/curriculum/",
    "University of Dayton: MSBN": "https://udayton.edu/business/graduate-academics/master_of_business_analytics/documents/mban-curriculum-updated.pdf",
    "University of Denver: MSDS": "https://ritchieonline.du.edu/data-science/curriculum/course-descriptions/",
    "University of Michigan: MSDS": "https://lsa.umich.edu/stats/masters_students/mastersprograms/data-science-masters-program.html",
    "University of Missouri: MSDS": "https://dsa.missouri.edu/curriculum/",
    "University of San Diego: Master of Advanced Study in Data Science": "https://jacobsschool.ucsd.edu/mas/dse/curriculum",
    "University of Virginia:  MSDS (non-dual)": "https://datascience.virginia.edu/pages/residential-msds-curriculum-21-22-non-dual",
    "University of Wisconsin: MSDS (Online)": "https://datasciencedegree.wisconsin.edu/data-science-program/data-science-courses/",
    "Wake Forest University: MSBA": "https://business.wfu.edu/masters-in-business-analytics/curriculum",
    "William and Mary: MSBA": "https://graduate.mason.wm.edu/msba/academics",
}
